version: 2.1
jobs:
  build_4_2_2:
    docker:
      - image: rocker/verse:4.2.2
    steps:
      - checkout
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE)"
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz
  
  build_4_1_0:
    docker:
      - image: rocker/verse:4.1.0
    steps:
      - checkout
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE)"
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_4_2_2
      - build_4_1_0
