version: 1
jobs:
  build:
    docker:
      - image: r-base:4.1.0
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: apt-get update
      - run:
          name: Install required libraries
          command: apt-get -y install libcurl4-gnutls-dev libxml2-dev libssl-dev
      -run:
          name: Install devtools
          command: R -e "install.packages(\"devtools\")"
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE)"
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz
